# Generated by Django 3.0 on 2026-05-19 15:05

from django.db import migrations


def copy_profile(apps, schema_editor):
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    NewProfile = apps.get_model('profiles', 'Profile')

    for old_profile in OldProfile.objects.all():
        NewProfile.objects.create(
            id=old_profile.id,
            favorite_city=old_profile.favorite_city,
            user_id=old_profile.user_id,
        )


def reverse_copy_profile(apps, schema_editor):
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    NewProfile = apps.get_model('profiles', 'Profile')

    for new_profile in NewProfile.objects.all():
        OldProfile.objects.create(
            id=new_profile.id,
            favorite_city=new_profile.favorite_city,
            user_id=new_profile.user_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('oc_lettings_site', '0001_initial')
    ]

    operations = [
        migrations.RunPython(copy_profile, reverse_copy_profile)
    ]
