# Generated by Django 3.0 on 2026-05-19 13:10

from django.db import migrations


def copy_addresses(apps, schema_editor):
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    NewAddress = apps.get_model('lettings', 'Address')

    for old_address in OldAddress.objects.all():
        NewAddress.objects.create(
            id=old_address.id,
            number=old_address.number,
            street=old_address.street,
            city=old_address.city,
            state=old_address.state,
            zip_code=old_address.zip_code,
            country_iso_code=old_address.country_iso_code,
        )


def reverse_copy_addresses(apps, schema_editor):
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    NewAddress = apps.get_model('lettings', 'Address')

    for new_address in NewAddress.objects.all():
        OldAddress.objects.create(
            id=new_address.id,
            number=new_address.number,
            street=new_address.street,
            city=new_address.city,
            state=new_address.state,
            zip_code=new_address.zip_code,
            country_iso_code=new_address.country_iso_code,
        )


def copy_lettings(apps, schema_editor):
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')
    NewLetting = apps.get_model('lettings', 'Letting')

    for old_letting in OldLetting.objects.all():
        NewLetting.objects.create(
            id=old_letting.id,
            title=old_letting.title,
            address_id=old_letting.address_id,
        )


def reverse_copy_lettings(apps, schema_editor):
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')
    NewLetting = apps.get_model('lettings', 'Letting')

    for new_letting in NewLetting.objects.all():
        OldLetting.objects.create(
            id=new_letting.id,
            title=new_letting.title,
            address_id=new_letting.address_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
        ('oc_lettings_site', '0001_initial')
    ]

    operations = [
        migrations.RunPython(copy_addresses, reverse_copy_addresses),
        migrations.RunPython(copy_lettings, reverse_copy_lettings),
    ]
