# Generated by Django 3.0 on 2026-05-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0003_auto_20260519_1704'),
        ('profiles', '0002_copy_profile')
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
